//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalDEBMargin
    {
        public int AdditionalDEBMarginId { get; set; }
        public int StateProvinceId { get; set; }
        public decimal MinRange { get; set; }
        public decimal MaxRange { get; set; }
        public decimal Value { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<int> UtilityId { get; set; }
        public string ZoneCode { get; set; }
        public int HedgeSalesEntityId { get; set; }
    
        public virtual StateProvince StateProvince { get; set; }
        public virtual Utility Utility { get; set; }
    }
}
