//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Sites = new HashSet<Site>();
            this.SiteServices = new HashSet<SiteService>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int AddressId { get; set; }
        public int StateProvinceId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
    
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<SiteService> SiteServices { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual StateProvince StateProvince { get; set; }
    }
}
