//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelPartnerDealSplit
    {
        public int ChannelPartnerDealSplitId { get; set; }
        public int OrgId { get; set; }
        public int OfferId { get; set; }
        public decimal SplitAmount { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
