//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public Claim()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int ClaimId { get; set; }
        public int ResourceId { get; set; }
        public int ClaimTypeId { get; set; }
    
        public virtual ClaimType ClaimType { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
