//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTemplateType
    {
        public ContractTemplateType()
        {
            this.ContractTemplates = new HashSet<ContractTemplate>();
            this.ContractTemplateMaps = new HashSet<ContractTemplateMap>();
        }
    
        public int ContractTemplateTypeId { get; set; }
        public string TemplateTypeCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ContractTemplate> ContractTemplates { get; set; }
        public virtual ICollection<ContractTemplateMap> ContractTemplateMaps { get; set; }
    }
}
