//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractStatusLog
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> PackageStartTime { get; set; }
        public Nullable<System.DateTime> PackageEndTime { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
