//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTemplate
    {
        public ContractTemplate()
        {
            this.ContractTemplateFields = new HashSet<ContractTemplateField>();
        }
    
        public int ContractTemplateId { get; set; }
        public string TemplateName { get; set; }
        public int ContractTemplateTypeId { get; set; }
        public int ContractTemplateMapId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string HtmlContent { get; set; }
        public byte[] BinaryContent { get; set; }
        public string Version { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
    
        public virtual ContractTemplateType ContractTemplateType { get; set; }
        public virtual ICollection<ContractTemplateField> ContractTemplateFields { get; set; }
        public virtual ContractTemplateMap ContractTemplateMap { get; set; }
    }
}
