//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTemplateField
    {
        public int ContractTemplateFieldId { get; set; }
        public int ContractTemplateId { get; set; }
        public string FieldName { get; set; }
        public string SourceSchemaName { get; set; }
        public string SourceTableName { get; set; }
        public string SourceColumnName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
    
        public virtual ContractTemplate ContractTemplate { get; set; }
    }
}
