//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public int PrimaryContactPhoneTypeId { get; set; }
        public bool IsPrimaryPhoneSmsEnabled { get; set; }
        public string SecondaryPhoneNumber { get; set; }
        public Nullable<int> SecondaryContactPhoneTypeId { get; set; }
        public Nullable<bool> IsSecondaryPhoneSmsEnabled { get; set; }
        public string FaxNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public string JobTitle { get; set; }
    
        public virtual ContactPhoneType ContactPhoneType { get; set; }
        public virtual ContactPhoneType ContactPhoneType1 { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
