//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDocumentType
    {
        public ContractDocumentType()
        {
            this.ContractDocuments = new HashSet<ContractDocument>();
        }
    
        public int ContractDocTypeId { get; set; }
        public string ContractDocTypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ContractDocument> ContractDocuments { get; set; }
    }
}
