//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTemplateMap
    {
        public ContractTemplateMap()
        {
            this.ContractTemplates = new HashSet<ContractTemplate>();
        }
    
        public int ContractTemplateMapId { get; set; }
        public int ContractTemplateTypeId { get; set; }
        public string StateProvinceCode { get; set; }
        public string ERMProductId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
    
        public virtual ContractTemplateType ContractTemplateType { get; set; }
        public virtual ICollection<ContractTemplate> ContractTemplates { get; set; }
    }
}
