//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.ContractDocuments = new HashSet<ContractDocument>();
        }
    
        public int ContractId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<decimal> HedgeContractId { get; set; }
        public Nullable<long> OfferPricingSubmissionId { get; set; }
        public string ThirdPartyVerificationNumber { get; set; }
        public string SlxTicketId { get; set; }
        public string AssignedAnalyst { get; set; }
        public Nullable<bool> SubmissionSuccessful { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> BookingSubmissionDate { get; set; }
    
        public virtual ICollection<ContractDocument> ContractDocuments { get; set; }
        public virtual OfferPricingSubmission OfferPricingSubmission { get; set; }
    }
}
