//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditHistory
    {
        public int CreditHistoryId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> CreditScore { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public int CreditStatusTypeId { get; set; }
        public System.DateTime CreditRequestDate { get; set; }
        public Nullable<System.DateTime> CreditApproveDate { get; set; }
        public Nullable<int> FinancialStressScore { get; set; }
        public Nullable<long> MaxApprovedUsage { get; set; }
        public Nullable<int> MaxApprovedTerm { get; set; }
        public string CreditApplicationNo { get; set; }
        public string DetailCreditResponse { get; set; }
        public Nullable<bool> HasInvoiceVerification { get; set; }
    
        public virtual CreditStatusType CreditStatusType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
