//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditStatusType
    {
        public CreditStatusType()
        {
            this.CreditHistories = new HashSet<CreditHistory>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int CreditStatusTypeId { get; set; }
        public string CreditStatusCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CreditHistory> CreditHistories { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
