//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDocument
    {
        public CustomerDocument()
        {
            this.SiteServiceCustomerDocuments = new HashSet<SiteServiceCustomerDocument>();
        }
    
        public int CustomerDocumentId { get; set; }
        public int CustomerId { get; set; }
        public int CustomerDocTypeId { get; set; }
        public string DescriptiveName { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public byte[] Document { get; set; }
        public string ContentType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SiteServiceCustomerDocument> SiteServiceCustomerDocuments { get; set; }
        public virtual CustomerDocumentType CustomerDocumentType { get; set; }
    }
}
