//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDocumentType
    {
        public CustomerDocumentType()
        {
            this.CustomerDocuments = new HashSet<CustomerDocument>();
        }
    
        public int CustomerDocTypeId { get; set; }
        public string CustomerDocTypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CustomerDocument> CustomerDocuments { get; set; }
    }
}
