//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        public CustomField()
        {
            this.StateProvinceCustomFieldMaps = new HashSet<StateProvinceCustomFieldMap>();
            this.CustomFieldValues = new HashSet<CustomFieldValue>();
        }
    
        public int CustomFieldId { get; set; }
        public string FieldName { get; set; }
    
        public virtual ICollection<StateProvinceCustomFieldMap> StateProvinceCustomFieldMaps { get; set; }
        public virtual ICollection<CustomFieldValue> CustomFieldValues { get; set; }
    }
}
