//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public EmailLog()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public int EmailLogId { get; set; }
        public System.DateTime SentDate { get; set; }
        public string SentTo { get; set; }
        public string Subject { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> EmailTemplateId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
