//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public EmailTemplate()
        {
            this.EmailLogs = new HashSet<EmailLog>();
        }
    
        public int EmailTemplateId { get; set; }
        public int EmailTypeId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string EmailTemplate1 { get; set; }
        public string ReplyTo { get; set; }
        public System.DateTime EffectiveStartDate { get; set; }
        public Nullable<System.DateTime> EffectiveEndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public string Subject { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        public virtual EmailType EmailType { get; set; }
        public virtual Role Role { get; set; }
    }
}
