//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentType
    {
        public EnrollmentType()
        {
            this.SiteServices = new HashSet<SiteService>();
        }
    
        public int EnrollmentTypeId { get; set; }
        public string EnrollmentTypeCode { get; set; }
        public string EnrollmentTypeName { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
    
        public virtual ICollection<SiteService> SiteServices { get; set; }
    }
}
