//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationLogging
    {
        public long ID { get; set; }
        public string ReferenceValue { get; set; }
        public string ReferenceName { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<long> OfferId { get; set; }
        public string RequestXML { get; set; }
        public string ResponseXML { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedUserId { get; set; }
    }
}
