//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISO
    {
        public ISO()
        {
            this.StructureDeskSettings = new HashSet<StructureDeskSetting>();
            this.UtilityServices = new HashSet<UtilityService>();
        }
    
        public int ISOId { get; set; }
        public string ISOName { get; set; }
        public string IsoCode { get; set; }
    
        public virtual ICollection<StructureDeskSetting> StructureDeskSettings { get; set; }
        public virtual ICollection<UtilityService> UtilityServices { get; set; }
    }
}
