//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixRequest
    {
        public MatrixRequest()
        {
            this.MatrixResponses = new HashSet<MatrixResponse>();
        }
    
        public int MatrixRequestId { get; set; }
        public System.Guid MatrixOfferGuid { get; set; }
        public string ContractPriceDate { get; set; }
        public string ContractStartDate { get; set; }
        public string ContractTerm { get; set; }
        public string VendorShortName { get; set; }
        public string RateCode { get; set; }
        public string Segment { get; set; }
        public string Zone { get; set; }
        public string AggGroup { get; set; }
        public string UsageMonth { get; set; }
        public string UsageAmount { get; set; }
        public string AnnualUsageAmount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> ModifyUserId { get; set; }
    
        public virtual ICollection<MatrixResponse> MatrixResponses { get; set; }
    }
}
