//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferDealSplit
    {
        public int OfferDealSplitID { get; set; }
        public int OfferId { get; set; }
        public int PersonId { get; set; }
        public decimal SplitPct { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual Person Person { get; set; }
    }
}
