//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferPricingStatusType
    {
        public OfferPricingStatusType()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public int OfferPricingStatusTypeId { get; set; }
        public string OfferPricingStatusName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
