//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public Offer()
        {
            this.ChannelPartnerDealSplits = new HashSet<ChannelPartnerDealSplit>();
            this.OfferRAROCResults = new HashSet<OfferRAROCResult>();
            this.OfferDetails = new HashSet<OfferDetail>();
            this.OfferDealSplits = new HashSet<OfferDealSplit>();
            this.OfferEvents = new HashSet<OfferEvent>();
            this.EmailLogs = new HashSet<EmailLog>();
        }
    
        public int OfferId { get; set; }
        public int EnteredByPersonId { get; set; }
        public int OwnedByPersonId { get; set; }
        public int CustomerId { get; set; }
        public int Term { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<decimal> BrokerFee { get; set; }
        public Nullable<decimal> AdditionalDebMargin { get; set; }
        public bool IsActive { get; set; }
        public string SourceSystemProductId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public decimal DebMargin { get; set; }
        public int OfferPricingStatusTypeId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ExactPrice { get; set; }
        public Nullable<decimal> TotalAveragePrice { get; set; }
        public bool IsProtected { get; set; }
        public bool ProtectionOverridden { get; set; }
        public int LanguageId { get; set; }
        public bool IsAccepted { get; set; }
        public bool ConsolidateBilling { get; set; }
        public Nullable<bool> IsExternallyPriced { get; set; }
        public Nullable<bool> IsRecommended { get; set; }
        public int PricingTypeId { get; set; }
    
        public virtual ICollection<ChannelPartnerDealSplit> ChannelPartnerDealSplits { get; set; }
        public virtual ICollection<OfferRAROCResult> OfferRAROCResults { get; set; }
        public virtual ICollection<OfferDetail> OfferDetails { get; set; }
        public virtual ICollection<OfferDealSplit> OfferDealSplits { get; set; }
        public virtual ICollection<OfferEvent> OfferEvents { get; set; }
        public virtual OfferPricingStatusType OfferPricingStatusType { get; set; }
        public virtual Person Person { get; set; }
        public virtual PricingType PricingType { get; set; }
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
    }
}
