//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferSheetPricing
    {
        public int OfferSheetPricingId { get; set; }
        public int OfferSheetId { get; set; }
        public long OfferPricingSubmissionId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
    
        public virtual OfferPricingSubmission OfferPricingSubmission { get; set; }
        public virtual OfferSheet OfferSheet { get; set; }
    }
}
