//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Customers = new HashSet<Customer>();
            this.ChannelPartnerDealSplits = new HashSet<ChannelPartnerDealSplit>();
            this.OrgAssignments = new HashSet<OrgAssignment>();
            this.SalesChannelTypes = new HashSet<SalesChannelType>();
        }
    
        public int OrgId { get; set; }
        public string OrgName { get; set; }
        public bool IsDirectEnergyOrg { get; set; }
        public Nullable<int> HedgeSalesEntityId { get; set; }
        public Nullable<decimal> MaxBrokerFee { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<ChannelPartnerDealSplit> ChannelPartnerDealSplits { get; set; }
        public virtual ICollection<OrgAssignment> OrgAssignments { get; set; }
        public virtual ICollection<SalesChannelType> SalesChannelTypes { get; set; }
    }
}
