//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgTermSetting
    {
        public OrgTermSetting()
        {
            this.Terms = new HashSet<Term>();
        }
    
        public int OrgTermSettingsId { get; set; }
        public int HedgeSalesEntityId { get; set; }
        public int StateProvinceId { get; set; }
        public Nullable<int> MaxMatrixTerm { get; set; }
        public Nullable<int> MaxDiscreteTerm { get; set; }
    
        public virtual StateProvince StateProvince { get; set; }
        public virtual ICollection<Term> Terms { get; set; }
    }
}
