//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAssignmentType
    {
        public PersonAssignmentType()
        {
            this.PersonAssignments = new HashSet<PersonAssignment>();
        }
    
        public int PersonAssignTypeId { get; set; }
        public string PersonAssignTypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PersonAssignment> PersonAssignments { get; set; }
    }
}
