//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.EmailLogs = new HashSet<EmailLog>();
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.Offers = new HashSet<Offer>();
            this.OfferDealSplits = new HashSet<OfferDealSplit>();
            this.ISRPoolMembers = new HashSet<ISRPoolMember>();
            this.OrgAssignments = new HashSet<OrgAssignment>();
            this.PersonAssignments = new HashSet<PersonAssignment>();
            this.PersonAssignments1 = new HashSet<PersonAssignment>();
        }
    
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.Guid DigitalUserGuid { get; set; }
        public Nullable<int> HedgeSalesEntityId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Customer> Customers1 { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<OfferDealSplit> OfferDealSplits { get; set; }
        public virtual ICollection<ISRPoolMember> ISRPoolMembers { get; set; }
        public virtual ICollection<OrgAssignment> OrgAssignments { get; set; }
        public virtual ICollection<PersonAssignment> PersonAssignments { get; set; }
        public virtual ICollection<PersonAssignment> PersonAssignments1 { get; set; }
        public virtual Role Role { get; set; }
    }
}
