//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricingType
    {
        public PricingType()
        {
            this.Offers = new HashSet<Offer>();
            this.Terms = new HashSet<Term>();
        }
    
        public int PricingTypeId { get; set; }
        public string PricingTypeName { get; set; }
    
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<Term> Terms { get; set; }
    }
}
