//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateCodeMap
    {
        public int RateCodeMapId { get; set; }
        public Nullable<int> StateProvinceId { get; set; }
        public Nullable<int> UtilityId { get; set; }
        public string PricingPortalRateCode { get; set; }
        public string HedgeRateCode { get; set; }
        public string MatrixRateCode { get; set; }
        public string MatrixSegment { get; set; }
    
        public virtual StateProvince StateProvince { get; set; }
        public virtual Utility Utility { get; set; }
    }
}
