//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.StateProvinces = new HashSet<StateProvince>();
        }
    
        public int RegionId { get; set; }
        public string RegionCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<StateProvince> StateProvinces { get; set; }
    }
}
