//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.People = new HashSet<Person>();
            this.EmailTemplates = new HashSet<EmailTemplate>();
            this.Claims = new HashSet<Claim>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDateUTC { get; set; }
        public System.Guid Code { get; set; }
        public System.Guid BaseRoleCode { get; set; }
        public bool IsInternal { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<EmailTemplate> EmailTemplates { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
    }
}
