//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerializedObject
    {
        public int SerializedObjectId { get; set; }
        public string XMLObject { get; set; }
        public string ReferenceValue { get; set; }
        public string ReferenceType { get; set; }
        public System.DateTime CreateTimeStamp { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string ObjectType { get; set; }
        public string ServiceReference { get; set; }
    }
}
