//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signature
    {
        public int SignatureId { get; set; }
        public string Code { get; set; }
        public bool IsEncrypted { get; set; }
        public byte[] Signature1 { get; set; }
    }
}
