//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteServiceFieldMap
    {
        public int TemplateId { get; set; }
        public int FieldId { get; set; }
        public string ColumnName { get; set; }
    
        public virtual SiteServiceField SiteServiceField { get; set; }
        public virtual SiteServiceTemplate SiteServiceTemplate { get; set; }
    }
}
