//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteServiceField
    {
        public SiteServiceField()
        {
            this.SiteServiceFieldMaps = new HashSet<SiteServiceFieldMap>();
        }
    
        public int SiteServiceFieldId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SiteServiceFieldMap> SiteServiceFieldMaps { get; set; }
    }
}
