//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site1
    {
        public Site1()
        {
            this.SiteService1 = new HashSet<SiteService1>();
        }
    
        public int SnapShotSiteId { get; set; }
        public int SnapShotCustomerId { get; set; }
        public int CountryId { get; set; }
        public string StateOrProvinceCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> TaxPct { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string SiteName { get; set; }
        public bool IsPriorityMoveIn { get; set; }
        public Nullable<bool> HasBuildingPermit { get; set; }
        public int ActualSiteId { get; set; }
    
        public virtual Customer1 Customer1 { get; set; }
        public virtual ICollection<SiteService1> SiteService1 { get; set; }
    }
}
