//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteServiceCustomerDocument
    {
        public int SiteSvcCustDocId { get; set; }
        public int CustomerDocumentId { get; set; }
        public int SiteServiceId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
    
        public virtual CustomerDocument CustomerDocument { get; set; }
        public virtual SiteService SiteService { get; set; }
    }
}
