//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.SiteServices = new HashSet<SiteService>();
        }
    
        public int SiteId { get; set; }
        public int CustomerId { get; set; }
        public int ServiceAddressId { get; set; }
        public string SiteName { get; set; }
        public bool IsPriorityMoveIn { get; set; }
        public Nullable<bool> HasBuildingPermit { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SiteService> SiteServices { get; set; }
    }
}
