//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteService
    {
        public SiteService()
        {
            this.HuRequests = new HashSet<HuRequest>();
            this.SiteServiceCustomerDocuments = new HashSet<SiteServiceCustomerDocument>();
            this.OfferDetails = new HashSet<OfferDetail>();
        }
    
        public int SiteServiceId { get; set; }
        public int UtilityServiceId { get; set; }
        public int SiteId { get; set; }
        public int BillingAddressId { get; set; }
        public Nullable<int> LoadFactorId { get; set; }
        public string LdcAcctNumber { get; set; }
        public string RateCode { get; set; }
        public long Volume { get; set; }
        public int VolumeUomId { get; set; }
        public string VolumeTimePeriodCode { get; set; }
        public bool LoeInEffect { get; set; }
        public Nullable<System.DateTime> LoeExpirationDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public string ZoneCode { get; set; }
        public string VolumeTimePeriodMonth { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> EnrollmentTypeId { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<System.DateTime> MonthlyVolumeDate { get; set; }
        public Nullable<long> MonthlyVolume { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Site Site { get; set; }
        public virtual EnrollmentType EnrollmentType { get; set; }
        public virtual LoadFactorType LoadFactorType { get; set; }
        public virtual ICollection<HuRequest> HuRequests { get; set; }
        public virtual ICollection<SiteServiceCustomerDocument> SiteServiceCustomerDocuments { get; set; }
        public virtual ICollection<OfferDetail> OfferDetails { get; set; }
        public virtual UnitOfMeasureType UnitOfMeasureType { get; set; }
        public virtual UtilityService UtilityService { get; set; }
    }
}
