//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceSystem
    {
        public int SourceSystemID { get; set; }
        public string SourceSystemName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> DisplayFlag { get; set; }
    }
}
