//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateProvinceCustomFieldMap
    {
        public int StateProvinceId { get; set; }
        public int CustomFieldId { get; set; }
        public bool IsMatrixPriceFilter { get; set; }
    
        public virtual CustomField CustomField { get; set; }
        public virtual StateProvince StateProvince { get; set; }
    }
}
