//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureDeskSetting
    {
        public int StructureDeskSettingId { get; set; }
        public int ISOId { get; set; }
        public string EligibleThreshold { get; set; }
        public int RequiredThreshold { get; set; }
    
        public virtual ISO ISO { get; set; }
    }
}
