//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSPThreshold
    {
        public TDSPThreshold()
        {
            this.UtilityTDSPs = new HashSet<UtilityTDSP>();
        }
    
        public int TDSPThesholdID { get; set; }
        public int TDSPThreshold1 { get; set; }
    
        public virtual ICollection<UtilityTDSP> UtilityTDSPs { get; set; }
    }
}
