//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PricingPortalEntities : DbContext
    {
        public PricingPortalEntities()
            : base("name=PricingPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EmailLog> EmailLogs { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<StructureDeskSetting> StructureDeskSettings { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<CreditHistory> CreditHistories { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerDocument> CustomerDocuments { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<SiteService> SiteServices { get; set; }
        public DbSet<SiteServiceCustomerDocument> SiteServiceCustomerDocuments { get; set; }
        public DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public DbSet<ChannelPartnerDealSplit> ChannelPartnerDealSplits { get; set; }
        public DbSet<IntegrationErrorLog> IntegrationErrorLogs { get; set; }
        public DbSet<IntegrationLogging> IntegrationLoggings { get; set; }
        public DbSet<SerializedObject> SerializedObjects { get; set; }
        public DbSet<AdditionalDEBMargin> AdditionalDEBMargins { get; set; }
        public DbSet<ChannelPartnerFee> ChannelPartnerFees { get; set; }
        public DbSet<Contract> Contracts { get; set; }
        public DbSet<ContractDocument> ContractDocuments { get; set; }
        public DbSet<DebMargin> DebMargins { get; set; }
        public DbSet<HuRequest> HuRequests { get; set; }
        public DbSet<HuRequestStatu> HuRequestStatus { get; set; }
        public DbSet<MatrixRequest> MatrixRequests { get; set; }
        public DbSet<MatrixResponse> MatrixResponses { get; set; }
        public DbSet<Offer> Offers { get; set; }
        public DbSet<OfferDealSplit> OfferDealSplits { get; set; }
        public DbSet<OfferDetail> OfferDetails { get; set; }
        public DbSet<OfferEvent> OfferEvents { get; set; }
        public DbSet<OfferPricingResult> OfferPricingResults { get; set; }
        public DbSet<OfferPricingSubmission> OfferPricingSubmissions { get; set; }
        public DbSet<OfferRAROCResult> OfferRAROCResults { get; set; }
        public DbSet<OfferSheet> OfferSheets { get; set; }
        public DbSet<OfferSheetPricing> OfferSheetPricings { get; set; }
        public DbSet<UtilityTDSP> UtilityTDSPs { get; set; }
        public DbSet<ISRPool> ISRPools { get; set; }
        public DbSet<ISRPoolMember> ISRPoolMembers { get; set; }
        public DbSet<OrgAllStatesOption> OrgAllStatesOptions { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<OrgAssignment> OrgAssignments { get; set; }
        public DbSet<OrgStateSetting> OrgStateSettings { get; set; }
        public DbSet<OrgTermSetting> OrgTermSettings { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PersonAssignment> PersonAssignments { get; set; }
        public DbSet<Term> Terms { get; set; }
        public DbSet<ContactPhoneType> ContactPhoneTypes { get; set; }
        public DbSet<ContactTitleType> ContactTitleTypes { get; set; }
        public DbSet<ContractDocumentType> ContractDocumentTypes { get; set; }
        public DbSet<ContractTemplateType> ContractTemplateTypes { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<CreditStatusType> CreditStatusTypes { get; set; }
        public DbSet<CustomerDocumentType> CustomerDocumentTypes { get; set; }
        public DbSet<CustomField> CustomFields { get; set; }
        public DbSet<CustomFieldValue> CustomFieldValues { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<EmailType> EmailTypes { get; set; }
        public DbSet<EnrollmentType> EnrollmentTypes { get; set; }
        public DbSet<ISO> ISOes { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<LoadFactorType> LoadFactorTypes { get; set; }
        public DbSet<OfferPricingStatusType> OfferPricingStatusTypes { get; set; }
        public DbSet<PersonAssignmentType> PersonAssignmentTypes { get; set; }
        public DbSet<PricingType> PricingTypes { get; set; }
        public DbSet<RateCodeMap> RateCodeMaps { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Regulatory> Regulatories { get; set; }
        public DbSet<SalesChannelType> SalesChannelTypes { get; set; }
        public DbSet<ServiceType> ServiceTypes { get; set; }
        public DbSet<Signature> Signatures { get; set; }
        public DbSet<SourceSystem> SourceSystems { get; set; }
        public DbSet<StateProvince> StateProvinces { get; set; }
        public DbSet<StateProvinceCustomFieldMap> StateProvinceCustomFieldMaps { get; set; }
        public DbSet<TDSPThreshold> TDSPThresholds { get; set; }
        public DbSet<UnitOfMeasureType> UnitOfMeasureTypes { get; set; }
        public DbSet<Utility> Utilities { get; set; }
        public DbSet<UtilityEmail> UtilityEmails { get; set; }
        public DbSet<UtilityService> UtilityServices { get; set; }
        public DbSet<UtilityValidationRule> UtilityValidationRules { get; set; }
        public DbSet<Utility1> Utility1 { get; set; }
        public DbSet<Claim> Claims { get; set; }
        public DbSet<ClaimType> ClaimTypes { get; set; }
        public DbSet<Resource> Resources { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<USER_SESSION> USER_SESSION { get; set; }
        public DbSet<Customer1> Customer1 { get; set; }
        public DbSet<Site1> Site1 { get; set; }
        public DbSet<SiteService1> SiteService1 { get; set; }
        public DbSet<ContractStatusChildLog> ContractStatusChildLogs { get; set; }
        public DbSet<ContractStatusLog> ContractStatusLogs { get; set; }
        public DbSet<CustomerDocumentStage> CustomerDocumentStages { get; set; }
        public DbSet<BrandProperty> BrandProperties { get; set; }
        public DbSet<ContractTemplate> ContractTemplates { get; set; }
        public DbSet<ContractTemplateField> ContractTemplateFields { get; set; }
        public DbSet<ContractTemplateMap> ContractTemplateMaps { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<SiteServiceField> SiteServiceFields { get; set; }
        public DbSet<SiteServiceFieldMap> SiteServiceFieldMaps { get; set; }
        public DbSet<SiteServiceTemplate> SiteServiceTemplates { get; set; }
    }
}
