//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int TermsId { get; set; }
        public int OrgTermSettingsId { get; set; }
        public Nullable<int> TermLength { get; set; }
        public int PricingTypeId { get; set; }
    
        public virtual OrgTermSetting OrgTermSetting { get; set; }
        public virtual PricingType PricingType { get; set; }
    }
}
