//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasureType
    {
        public UnitOfMeasureType()
        {
            this.SiteServices = new HashSet<SiteService>();
            this.OfferDetails = new HashSet<OfferDetail>();
        }
    
        public int UomId { get; set; }
        public string UomCode { get; set; }
        public string UomName { get; set; }
    
        public virtual ICollection<SiteService> SiteServices { get; set; }
        public virtual ICollection<OfferDetail> OfferDetails { get; set; }
    }
}
