//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SESSION
    {
        public long ID { get; set; }
        public System.Guid TOKEN { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
        public byte[] USER_DATA { get; set; }
    }
}
