//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityValidationRule
    {
        public int UtilityValidationRuleId { get; set; }
        public int UtilityServiceId { get; set; }
        public string AccountNumberRegEx { get; set; }
        public string AccountNumberDescription { get; set; }
        public string AccountNumberMask { get; set; }
        public string AccountNumberPrefix { get; set; }
    
        public virtual UtilityService UtilityService { get; set; }
    }
}
