//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityService
    {
        public UtilityService()
        {
            this.SiteServices = new HashSet<SiteService>();
            this.UtilityValidationRules = new HashSet<UtilityValidationRule>();
        }
    
        public int UtilityServiceId { get; set; }
        public int UtilityId { get; set; }
        public int ServiceTypeId { get; set; }
        public int StateProvinceId { get; set; }
        public string AccountNumberRegEx { get; set; }
        public string AccountNumberDescription { get; set; }
        public string AccountNumberMask { get; set; }
        public Nullable<int> IsoId { get; set; }
    
        public virtual ICollection<SiteService> SiteServices { get; set; }
        public virtual ISO ISO { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual StateProvince StateProvince { get; set; }
        public virtual Utility Utility { get; set; }
        public virtual ICollection<UtilityValidationRule> UtilityValidationRules { get; set; }
    }
}
