//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utility1
    {
        public int UtilityId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string DUNS { get; set; }
    }
}
