//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utility
    {
        public Utility()
        {
            this.AdditionalDEBMargins = new HashSet<AdditionalDEBMargin>();
            this.ChannelPartnerFees = new HashSet<ChannelPartnerFee>();
            this.DebMargins = new HashSet<DebMargin>();
            this.UtilityTDSPs = new HashSet<UtilityTDSP>();
            this.RateCodeMaps = new HashSet<RateCodeMap>();
            this.UtilityServices = new HashSet<UtilityService>();
        }
    
        public int UtilityId { get; set; }
        public string Name { get; set; }
        public string Abrevation { get; set; }
        public string DUNS { get; set; }
    
        public virtual ICollection<AdditionalDEBMargin> AdditionalDEBMargins { get; set; }
        public virtual ICollection<ChannelPartnerFee> ChannelPartnerFees { get; set; }
        public virtual ICollection<DebMargin> DebMargins { get; set; }
        public virtual ICollection<UtilityTDSP> UtilityTDSPs { get; set; }
        public virtual ICollection<RateCodeMap> RateCodeMaps { get; set; }
        public virtual ICollection<UtilityService> UtilityServices { get; set; }
    }
}
